
    get:
      tags:
        - admin
      summary: /api/admin/advanced/database
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      redis:
                        type: object
                        properties:
                          aof_current_rewrite_time_sec:
                            type: string
                          aof_enabled:
                            type: string
                          aof_last_bgrewrite_status:
                            type: string
                          aof_last_rewrite_time_sec:
                            type: string
                          aof_rewrite_in_progress:
                            type: string
                          aof_rewrite_scheduled:
                            type: string
                          arch_bits:
                            type: string
                          blocked_clients:
                            type: string
                          client_biggest_input_buf:
                            type: string
                          client_longest_output_list:
                            type: string
                          config_file:
                            type: string
                          connected_clients:
                            type: string
                          connected_slaves:
                            type: string
                          db0:
                            type: string
                          evicted_keys:
                            type: string
                          expired_keys:
                            type: string
                          gcc_version:
                            type: string
                          hz:
                            type: string
                          instantaneous_ops_per_sec:
                            type: string
                          keyspace_hits:
                            type: string
                          keyspace_misses:
                            type: string
                          latest_fork_usec:
                            type: string
                          loading:
                            type: string
                          lru_clock:
                            type: string
                          master_repl_offset:
                            type: string
                          mem_allocator:
                            type: string
                          mem_fragmentation_ratio:
                            type: string
                          multiplexing_api:
                            type: string
                          os:
                            type: string
                          process_id:
                            type: string
                          pubsub_channels:
                            type: string
                          pubsub_patterns:
                            type: string
                          rdb_bgsave_in_progress:
                            type: string
                          rdb_changes_since_last_save:
                            type: string
                          rdb_current_bgsave_time_sec:
                            type: string
                          rdb_last_bgsave_status:
                            type: string
                          rdb_last_bgsave_time_sec:
                            type: string
                          rdb_last_save_time:
                            type: string
                          redis_build_id:
                            type: string
                          redis_git_dirty:
                            type: string
                          redis_git_sha1:
                            type: string
                          redis_mode:
                            type: string
                          redis_version:
                            type: string
                          rejected_connections:
                            type: string
                          repl_backlog_active:
                            type: string
                          repl_backlog_first_byte_offset:
                            type: string
                          repl_backlog_histlen:
                            type: string
                          repl_backlog_size:
                            type: string
                          role:
                            type: string
                          run_id:
                            type: string
                          sync_full:
                            type: string
                          sync_partial_err:
                            type: string
                          sync_partial_ok:
                            type: string
                          tcp_port:
                            type: string
                          total_commands_processed:
                            type: string
                          total_connections_received:
                            type: string
                          uptime_in_days:
                            type: string
                          uptime_in_seconds:
                            type: string
                          used_cpu_sys:
                            type: string
                          used_cpu_sys_children:
                            type: string
                          used_cpu_user:
                            type: string
                          used_cpu_user_children:
                            type: string
                          used_memory:
                            type: string
                          used_memory_human:
                            type: string
                          used_memory_lua:
                            type: string
                          used_memory_peak:
                            type: string
                          used_memory_peak_human:
                            type: string
                          used_memory_rss:
                            type: string
                          keys:
                            type: string
                          expires:
                            type: string
                          avg_ttl:
                            type: string
                          instantaneous_input:
                            type: string
                          instantaneous_output:
                            type: string
                          total_net_input:
                            type: string
                          total_net_output:
                            type: string
                          raw:
                            type: string
                          redis:
                            type: boolean
                      mongo:
                        type: object
                        properties:
                          db:
                            type: string
                          collections:
                            type: number
                          objects:
                            type: number
                          avgObjSize:
                            type: string
                          dataSize:
                            type: string
                          storageSize:
                            type: string
                          numExtents:
                            type: number
                          indexes:
                            type: number
                          indexSize:
                            type: string
                          ok:
                            type: number
                          mem:
                            type: object
                            properties:
                              bits:
                                type: number
                              resident:
                                type: string
                              virtual:
                                type: string
                              supported:
                                type: boolean
                              mapped:
                                type: string
                              mappedWithJournal:
                                type: number
                          collectionData:
                            type: array
                            items:
                              type: object
                              properties:
                                name:
                                  type: string
                                count:
                                  type: number
                                size:
                                  type: number
                                avgObjSize:
                                  type: number
                                storageSize:
                                  type: number
                                totalIndexSize:
                                  type: number
                                indexSizes:
                                  type: object
                                  properties:
                                    _id_:
                                      type: number
                                    expireAt_1:
                                      type: number
                                    _key_1_score_-1:
                                      type: number
                                    _key_1_value_-1:
                                      type: number
                                    content_text_uid_1_cid_1:
                                      type: number
                          network:
                            type: object
                            properties:
                              bytesIn:
                                type: string
                              bytesOut:
                                type: string
                              numRequests:
                                type: string
                          raw:
                            type: string
                          fileSize:
                            type: number
                          storageEngine:
                            type: string
                          host:
                            type: string
                          version:
                            type: string
                          uptime:
                            type: number
                          mongo:
                            type: boolean