
    get:
      tags:
        - home
      summary: /api/config
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  relative_path:
                    type: string
                  upload_url:
                    type: string
                  siteTitle:
                    type: string
                  browserTitle:
                    type: string
                  titleLayout:
                    type: string
                  showSiteTitle:
                    type: boolean
                  minimumTitleLength:
                    type: number
                  maximumTitleLength:
                    type: number
                  minimumPostLength:
                    type: number
                  maximumPostLength:
                    type: number
                  minimumTagsPerTopic:
                    type: number
                  maximumTagsPerTopic:
                    type: number
                  minimumTagLength:
                    type: number
                  maximumTagLength:
                    type: number
                  useOutgoingLinksPage:
                    type: boolean
                  allowGuestHandles:
                    type: boolean
                  allowFileUploads:
                    type: boolean
                  allowTopicsThumbnail:
                    type: boolean
                  usePagination:
                    type: boolean
                  disableChat:
                    type: boolean
                  disableChatMessageEditing:
                    type: boolean
                  maximumChatMessageLength:
                    type: number
                  socketioTransports:
                    type: array
                    items:
                      type: string
                  socketioOrigins:
                    type: string
                  websocketAddress:
                    type: string
                  maxReconnectionAttempts:
                    type: number
                  reconnectionDelay:
                    type: number
                  topicsPerPage:
                    type: number
                  postsPerPage:
                    type: number
                  maximumFileSize:
                    type: number
                  theme:id:
                    type: string
                  theme:src:
                    type: string
                  defaultLang:
                    type: string
                  userLang:
                    type: string
                  loggedIn:
                    type: boolean
                  uid:
                    type: number
                    description: A user identifier
                  cache-buster:
                    type: string
                  requireEmailConfirmation:
                    type: boolean
                  topicPostSort:
                    type: string
                  categoryTopicSort:
                    type: string
                  csrf_token:
                    type: string
                  searchEnabled:
                    type: boolean
                  bootswatchSkin:
                    type: string
                  enablePostHistory:
                    type: boolean
                  notificationAlertTimeout:
                    type: number
                  timeagoCutoff:
                    type: number
                  timeagoCodes:
                    type: array
                    items:
                      type: string
                  cookies:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                      message:
                        type: string
                      dismiss:
                        type: string
                      link:
                        type: string
                      link_url:
                        type: string
                  acpLang:
                    type: string
                  topicSearchEnabled:
                    type: boolean
                  hideSubCategories:
                    type: boolean
                  hideCategoryLastPost:
                    type: boolean
                  enableQuickReply:
                    type: boolean
                  markdown:
                    type: object
                    properties:
                      highlight:
                        type: number
                      highlightLinesLanguageList:
                        type: array
                        items: {}
                      theme:
                        type: string
                  question-and-answer:
                    type: object
                    properties:
                      defaultCid_13:
                        type: string
                      defaultCid_1:
                        type: string
                      defaultCid_5:
                        type: string
                      forceQuestions:
                        type: string
                      defaultCid_2:
                        type: string
                      defaultCid_6:
                        type: string
                      defaultCid_3:
                        type: string
                      defaultCid_15:
                        type: string
                      defaultCid_7:
                        type: string
                      defaultCid_10:
                        type: string
                      defaultCid_16:
                        type: string
                      defaultCid_21:
                        type: string
                      defaultCid_8:
                        type: string
                      defaultCid_4:
                        type: string
                      defaultCid_14:
                        type: string
                      defaultCid_17:
                        type: string
                      defaultCid_18:
                        type: string
                      defaultCid_19:
                        type: string
                      defaultCid_20:
                        type: string
                      defaultCid_22:
                        type: string
                      defaultCid_26:
                        type: string
                  composer-default:
                    type: object
                    properties: {}
                  sso-google:
                    type: object
                    properties:
                      style:
                        type: string